/*namespace SecretAPI.CodeGeneration.Utils;

using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

public static class WritingUtils
{
    public static string GetAccessibilityString(this Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.ProtectedAndInternal => "protected internal",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            _ => throw new ArgumentOutOfRangeException(nameof(accessibility), accessibility, "Accessibility not supported")
        };
    }

    public static IndentedTextWriter WriteGeneratedText(this IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine($"// Generated {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        writer.WriteLine();
        return writer;
    }

    public static IndentedTextWriter WriteNamespace(this IndentedTextWriter writer, INamedTypeSymbol symbol, bool startBrace)
    {
        if (symbol.ContainingNamespace == null)
            return writer;
        
        writer.WriteLine($"namespace {symbol.ContainingNamespace}");
        if (startBrace)
            WriteStartBrace(writer);

        return writer;
    }

    public static IndentedTextWriter WriteUsings(this IndentedTextWriter writer, params string[] usings)
    {
        if (usings.Length == 0)
            return writer;

        foreach (string @using in usings)
            writer.WriteLine($"using {@using};");

        writer.WriteLine();
        return writer;
    }

    public static IndentedTextWriter WritePartialClass(this IndentedTextWriter writer, string className, bool startBrace)
    {
        writer.WriteLine($"partial class {className}");
        if (startBrace)
        {
            writer.WriteLine("{");
            writer.Indent++;
        }

        return writer;
    }

    public static IndentedTextWriter WriteMethod(
        this IndentedTextWriter writer,
        string methodName,
        string returnType,
        bool isOverride,
        Accessibility accessibility,
        bool startBrace,
        params string[] parameters)
    {
        writer.Write(GetAccessibilityString(accessibility));
        if (isOverride)
            writer.Write(" override ");
        writer.Write(returnType);
        writer.Write(" " +  methodName);
        writer.WriteLine("(");
        writer.Indent++;

        for (int index = 0; index < parameters.Length; index++)
        {
            string parameter = parameters[index];
            if (parameters.Length > index + 1)
                writer.WriteLine(parameter + ",");
            else if (!startBrace)
                writer.Write(parameter + ")");
            else
                writer.WriteLine(parameter + ")");
        }

        writer.Indent--;

        if (startBrace)
            writer.WriteStartBrace();

        return writer;
    }

    public static IndentedTextWriter WriteStartBrace(this IndentedTextWriter writer)
    {
        writer.WriteLine("{");
        writer.Indent++;
        return writer;
    }

    public static IndentedTextWriter FinishAllIndentations(this IndentedTextWriter writer)
    {
        while (writer.Indent > 0)
        {
            writer.Indent--;
            writer.WriteLine("}");
        }

        return writer; 
    }
}*/