namespace SecretAPI.SourceGenerators.Builders;

internal class ClassBuilder : Builder<ClassBuilder>
{
    private NamespaceDeclarationSyntax _namespaceDeclaration;
    private ClassDeclarationSyntax _classDeclaration;

    private readonly List<UsingDirectiveSyntax> _usings = new();
    private readonly List<MethodDeclarationSyntax> _methods = new();

    private ClassBuilder(NamespaceDeclarationSyntax namespaceDeclaration, ClassDeclarationSyntax classDeclaration)
    {
        _namespaceDeclaration = namespaceDeclaration;
        _classDeclaration = classDeclaration;

        AddUsingStatements("System.CodeDom.Compiler");
    }

    internal static ClassBuilder CreateBuilder(INamedTypeSymbol namedClass)
        => CreateBuilder(NamespaceDeclaration(ParseName(namedClass.ContainingNamespace.ToDisplayString())), ClassDeclaration(namedClass.Name));

    internal static ClassBuilder CreateBuilder(NamespaceDeclarationSyntax namespaceDeclaration, ClassDeclarationSyntax classDeclaration)
        => new(namespaceDeclaration, classDeclaration);

    internal ClassBuilder AddUsingStatements(params string[] usingStatements)
    {
        foreach (string statement in usingStatements)
        {
            UsingDirectiveSyntax usings = UsingDirective(ParseName(statement));
            if (!_usings.Any(existing => existing.IsEquivalentTo(usings)))
                _usings.Add(usings);
        }

        return this;
    }

    internal MethodBuilder StartMethodCreation(string methodName, TypeSyntax returnType) => new(this, methodName, returnType);
    internal MethodBuilder StartMethodCreation(string methodName, SyntaxKind returnType) => StartMethodCreation(methodName, GetPredefinedTypeSyntax(returnType));

    internal void AddMethodDefinition(MethodDeclarationSyntax method) => _methods.Add(method);

    internal CompilationUnitSyntax Build()
    {
        _classDeclaration = _classDeclaration
            .AddAttributeLists(GetGeneratedCodeAttributeListSyntax())
            .AddModifiers(_modifiers.ToArray())
            .AddMembers(_methods.Cast<MemberDeclarationSyntax>().ToArray());

        _namespaceDeclaration = _namespaceDeclaration
            .AddUsings(_usings.ToArray())
            .AddMembers(_classDeclaration);

        return CompilationUnit()
            .AddMembers(_namespaceDeclaration)
            .NormalizeWhitespace()
            .WithLeadingTrivia(Comment("// <auto-generated>"), LineFeed, Comment("#pragma warning disable"), LineFeed, Comment("#nullable enable"), LineFeed, LineFeed);
    }

    internal void Build(SourceProductionContext context, string name) => context.AddSource(name, Build().ToFullString());
}