namespace SecretAPI.CodeGeneration.CodeBuilders;

internal class ClassBuilder
{
    private NamespaceDeclarationSyntax _namespaceDeclaration;
    private ClassDeclarationSyntax _classDeclaration;
    private string _className;

    private readonly List<SyntaxToken> _modifiers = new();
    private readonly List<UsingDirectiveSyntax> _usings = new();
    private readonly List<MethodDeclarationSyntax> _methods = new();

    private ClassBuilder(string @namespace, string className)
    {
        _namespaceDeclaration = NamespaceDeclaration(ParseName(@namespace));
        _className = className;
        _classDeclaration = ClassDeclaration(className);

        AddUsingStatements("System.CodeDom.Compiler");
    }
    
    internal static ClassBuilder CreateBuilder(string @namespace, string className)
        => new(@namespace, className);

    internal static ClassBuilder CreateBuilder(INamedTypeSymbol namedClass)
        => new(namedClass.ContainingNamespace.ToDisplayString(), namedClass.Name);

    internal ClassBuilder AddUsingStatements(params string[] usingStatement)
    {
        foreach (string statement in usingStatement)
            _usings.Add(UsingDirective(ParseName(statement)));

        return this;
    }

    internal MethodBuilder StartMethodCreation(string methodName, string returnType) => new(this, methodName, returnType);

    internal void AddMethodDefinition(MethodDeclarationSyntax method) => _methods.Add(method);

    internal ClassBuilder AddModifiers(params SyntaxKind[] modifiers)
    {
        foreach (SyntaxKind token in modifiers)
            _modifiers.Add(Token(token));

        return this;
    }

    internal CompilationUnitSyntax Build()
    {
        _classDeclaration = _classDeclaration
            .AddAttributeLists(GetGeneratedCodeAttributeListSyntax())
            .AddModifiers(_modifiers.ToArray())
            .AddMembers(_methods.Cast<MemberDeclarationSyntax>().ToArray());

        _namespaceDeclaration = _namespaceDeclaration
            .AddUsings(_usings.ToArray())
            .AddMembers(_classDeclaration);

        return CompilationUnit()
            .AddMembers(_namespaceDeclaration)
            .NormalizeWhitespace()
            .WithLeadingTrivia(Comment("// <auto-generated>"), LineFeed, Comment("#pragma warning disable"), LineFeed, LineFeed);
    }
}