namespace SecretAPI.CodeGeneration.CodeBuilders;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

internal class ClassBuilder
{
    private NamespaceDeclarationSyntax _namespaceDeclaration;
    private ClassDeclarationSyntax _classDeclaration;
    private string _className;

    private readonly List<SyntaxToken> _modifiers = new();
    private readonly List<UsingDirectiveSyntax> _usings = new();
    private readonly List<MethodDeclarationSyntax> _methods = new();

    private ClassBuilder(string @namespace, string className)
    {
        _namespaceDeclaration = SyntaxFactory.NamespaceDeclaration(SyntaxFactory.ParseName(@namespace));
        _className = className;
        _classDeclaration = SyntaxFactory.ClassDeclaration(className);
    }
    
    internal static ClassBuilder CreateBuilder(string @namespace, string className)
        => new(@namespace, className);

    internal static ClassBuilder CreateBuilder(INamedTypeSymbol namedClass)
        => new(namedClass.ContainingNamespace.ToDisplayString(), namedClass.Name);

    internal ClassBuilder AddUsingStatement(string usingStatement)
    {
        _usings.Add(SyntaxFactory.UsingDirective(SyntaxFactory.ParseName(usingStatement)));
        return this;
    }

    internal MethodBuilder AddMethodDefinition()
    {
        return new MethodBuilder(this);
    }

    internal ClassBuilder AddModifiers(params SyntaxKind[] modifiers)
    {
        foreach (SyntaxKind token in modifiers)
            AddModifier(token);

        return this;
    }

    internal ClassBuilder AddModifier(SyntaxKind syntax)
    {
        if (!_modifiers.Any(m => m.IsKind(syntax)))
            _modifiers.Add(SyntaxFactory.Token(syntax));

        return this;
    }

    internal void AddMethodDefinition(MethodDeclarationSyntax method) => _methods.Add(method);

    internal CompilationUnitSyntax Build()
    {
        _classDeclaration = _classDeclaration.AddModifiers(_modifiers.ToArray());

        _namespaceDeclaration = _namespaceDeclaration
            /*.WithLeadingTrivia(SyntaxFactory.Comment("// <auto-generated>"), SyntaxFactory.LineFeed, SyntaxFactory.LineFeed)*/
            .AddUsings(_usings.ToArray())
            .AddMembers(_classDeclaration);

        return SyntaxFactory.CompilationUnit()
            .AddMembers(_namespaceDeclaration)
            .NormalizeWhitespace()
            .WithLeadingTrivia(SyntaxFactory.Comment("// <auto-generated>"), SyntaxFactory.LineFeed, SyntaxFactory.LineFeed);
    }
}