namespace SecretAPI.CodeGeneration;

using System.CodeDom.Compiler;
using Microsoft.CodeAnalysis;

public static class WritingUtils
{
    public static string GetAccessibilityString(this Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Private => "private",
            Accessibility.ProtectedAndInternal => "protected internal",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.Public => "public",
            _ => throw new ArgumentOutOfRangeException(nameof(accessibility), accessibility, "Accessibility not supported")
        };
    }

    public static IndentedTextWriter WriteGeneratedText(this IndentedTextWriter writer)
    {
        writer.WriteLine("// <auto-generated>");
        writer.WriteLine($"// Generated {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        writer.WriteLine();
        return writer;
    }

    public static IndentedTextWriter WriteNamespace(this IndentedTextWriter writer, INamedTypeSymbol symbol, bool startBrace)
    {
        writer.WriteLine($"namespace {symbol.ContainingNamespace}");
        if (startBrace)
        {
            writer.WriteLine("{");
            writer.Indent++;
        }

        return writer;
    }

    public static IndentedTextWriter WriteUsings(this IndentedTextWriter writer, params string[] usings)
    {
        if (usings.Length == 0)
            return writer;
        
        foreach (string @using in usings)
            writer.WriteLine($"using {@using};");

        writer.WriteLine();

        return writer;
    }
}