name: Push Nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    env:
      REFERENCES_PATH: ${{ github.workspace }}/References
      BUILD_OUTPUT: ${{ github.workspace }}/Output

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4.0.1

      - name: Download SCP:SL References
        uses: Axwabo/scpsl-references-downloader@v1
        id: refs
        with:
          directory: $ {{ env.REFERENCES_PATH }}

      - name: Build and Pack NuGet
        env:
          SL_REFERENCES: ${{ steps.refs.outputs.target }}
        run: dotnet build -c Release --output ${{ env.BUILD_OUTPUT }}

      - name: Push NuGet package
        working-directory: ${{ env.BUILD_OUTPUT }}
        run: dotnet nuget push SecretAPI.*.nupkg