name: Push Nuget

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      REFERENCES_URL: https://exmod-team.github.io/SL-References/Dev.zip
      REFERENCES_PATH: ${{ github.workspace }}/References
      PACKAGED_PATH: ${{ github.workspace }}/Package

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4.0.1

      - name: Download References
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri ${{ env.REFERENCES_URL }} -OutFile "${{ github.workspace }}/References.zip"
          Expand-Archive -Path "${{ github.workspace }}/References.zip" -DestinationPath ${{ env.REFERENCES_PATH }}

      - name: Build and Pack NuGet
        env:
          SL_REFERENCES: ${{ env.REFERENCES_PATH }}
        run: dotnet pack -c Release --output ${PACKAGED_PATH}

      - name: Push NuGet package
        run: |
          $PackageFile = (Get-ChildItem -Path "${GITHUB_WORKSPACE}/nupkgs" -Include 'SecretAPI.*.nupkg' -Recurse | Select-Object -First 1).FullName
          dotnet nuget push $PackageFile --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json