name: Pull Request CI

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest
    
    env:
      REFERENCES_PATH: ${{ github.workspace }}/References
      BUILD_OUTPUT: ${{ github.workspace }}/Output

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4.0.1

      - name: Download SCP:SL References
        uses: Axwabo/scpsl-references-downloader@v1
        id: refs
        with:
          directory: $ {{ env.REFERENCES_PATH }}

      - name: Build
        env:
          SL_REFERENCES: ${{ steps.refs.outputs.target }}
        run: dotnet build -c Release --output  ${{ env.BUILD_OUTPUT }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Build Result
          path: ${{ env.BUILD_OUTPUT }}
          retention-days: 7